version: "3.9"

services:
  tensorflow_asr:
    build:
      context: .
      args:
        using_gpu: "true"
        install_rnnt_loss: "true"
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    ipc: "host"
    ports:
      - 6006:6006